### ISSUE TITLE
storageClass spec value is ignored

### ISSUE THREAD

**Issue by ankon** [krallistic/kafka-operator#37]
The value for the `storageClass` spec option is completely ignored, and instead the operator produces PVCs with a 'standard' storage class.

```yaml
kind: Kafkacluster
apiVersion: krallistic.github.com/v1
metadata:
  name: kafka
spec:
  brokerCount: 3
  zookeeperConnect: zookeeper.default.svc.cluster.local
  storageClass: slow
```

I'm suspecting this patch will fix that, but I cannot even get `dep ensure` to work, and removing the constraints leads to build failures.

```patch
diff --git a/util/util.go b/util/util.go
--- a/util/util.go
+++ b/util/util.go
@@ -391,7 +391,7 @@ func (c *ClientUtil) createStsFromSpec(cluster spec.Kafkacluster) *appsv1Beta1.S
 	replicas := cluster.Spec.BrokerCount
 	image := cluster.Spec.Image
 
-	storageClass := "standard"
+	storageClass := cluster.Spec.StorageClass
 
 	//TODO error handling, default value?
 	cpus, err := resource.ParseQuantity(cluster.Spec.Resources.CPU)
```
