### ISSUE TITLE
Fail to create CRD on start

### ISSUE THREAD

**Issue by fiftoine** [krallistic/kafka-operator#46]
Hi,

As is, the operator can't create CRDs if not given some permissions. 

Applying this makes it work (assuming you deploy on the default namespace) : 

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-kafka
rules:
- apiGroups:
  - krallistic.github.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-operator-kafka
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator-kafka
  apiGroup: rbac.authorization.k8s.io

```
